server:
  port: 8888



logging:
  level:
    org:
      springframework: DEBUG
spring:
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/Domin/OneDrive/Desktop/Spring/configServer/configServer

        default-label: master